# Generated by Django 5.2.1 on 2025-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(None, 'Не указано'), (True, 'Да'), (False, 'Нет')], default=None, verbose_name='Новостройка'),
        ),
    ]
