# Generated by Django 5.2.1 on 2025-05-29 10:18

from django.db import migrations


def set_new_building_status(apps):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= 2015 if flat.construction_year else None
        flat.save(update_fields=['new_building'])


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]
    operations = [migrations.RunPython(set_new_building_status)
    ]
