# Generated by Django 2.2.24 on 2025-06-05 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20250605_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes_by', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
