# Generated by Django 2.2.24 on 2025-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20250605_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
    ]
